### ISSUE TITLE
Custom on/off

### ISSUE THREAD

**Issue by thatisuday** [codekraft-studio/angular-page-loader#1]
Is there any way to show and hide loader programmatically? This will help a lot when ui has to block on user action like form submit

**Comment by codekraft-studio** [comment]
@thatisuday 

~actually right now is not possible, I will implement soon a service to do this, since is a good feature. thanks I'll update you~

__Edit:__ I just realized It was possible since the beginning, you can use the "flag" mode, by using that it will use the manual mode instead of the route interceptor.
For now I think this is the best solution, in future I will implement a service that can handle both cases so using the __flag__ mode will not stop the route interceptor from working later.

in your html:
```html
<page-loader flag="isLoading"></page-loader>
```

in your controller:
```javascript
angular.module('app')
.controller(function($scope) {

$scope.onSubmit = function() {
  
  // show the loader  <-----
  $scope.isLoading = true;

  // do something with your form
  // like sending form data to http service
  $http.post(url, data).then(function(resp) {
    
    // here you can turn off the loader  <-----
    $scope.isLoading = false;

    // and also redirect or do what you want
    $location.path('/home');
  }); 

}

});
```
